audit_header: false
title: Silicon Valley Real Estate Video Blog with Sophie Shen
description: >-
  Our mission at Sophie Shen Real Estate Team is to be your best resource for
  Silicon Valley real estate advice. Whether you are a buyer, seller, or
  investor, our team of professionals can answer any questions you might have
  about real estate. If you are looking to buy or sell a home, you can get all
  the information and the latest updates, tips, and tricks from The Sophie Shen
  Real Estate Team, your professional Silicon Valley Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Sophie Shen
  title: CalBRE 01837259
  license_number:
  about_markdown: >-
    Every time you buy or sell a house, it's a big project to you. This is where
    I can apply my skills and experience in project management for you. I will
    treat your buying and selling process as any large projects I managed for
    the fortune 500 companies I worked for. I will not only provide you with a
    clearly specified time line of all the milestones and tasks but also
    coordinate with all the third parties involved to make it a smooth and
    worry-free process for you.
  brand: Sophie Shen Real Estate Team
  brokerage:
  market: Silicon Valley
  address: '1525 McCarthy Blvd #1000 Milpitas, CA 95035'
  phone: 408-799-2558
  phone_type:
  phone2:
  phone2_type:
  email: sophie@sophierealestate.com
  url: 'https://www.sophierealestate.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.sophierealestate.com/cma/property-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.sophierealestate.com/search/advanced_search/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Silicon Valley Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'https://www.sophierealestate.com/cma/property-valuation/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Silicon Valley Home?
    CTA_text2: Search the entire MLS for your Silicon Valley home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.sophierealestate.com/search/advanced_search/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Silicon-Valley-Housing-Post-206028082761178/'
  linkedin_url:
  youtube_url: 'https://www.youtube.com/user/SophieTheRealtor'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Realtor-Sophie/#reviews'
  trulia_url:
  google_reviews_url: >-
    https://www.google.com/search?q=Sophie+Shen+Real+Estate&oq=Sophie+Shen+Real+Estate&aqs=chrome..69i57j69i59j69i60j69i61j69i60.431j0j7&sourceid=chrome&ie=UTF-8#lrd=0x808fcc05ab16d3f9:0x84856bc0016ff145,1,,,
  yelp_url:
  podcast_url:
podcast:
  title: Silicon Valley Real Estate Podcast with Sophie Shen
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Silicon
    Valley Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Sophie Shen Real Estate Team - your
    professional Silicon Valley Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Silicon Valley,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Sophie Shen
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Inside Silicon Valley<br>Real Estate
  hero_background_hex: '#efe9e9'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#8e0e0e'
  theme_color: '#8c8c8c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'